### ISSUE TITLE
Build Issue

### ISSUE THREAD

**Issue by yzhang71** [SanRazor-repo/SanRazor#3]
Hi team,
I am building this project on Ubuntu-18.04. After "./build_and_install_llvm9.sh", where can I find "SanRazor-clang"? Thanks!

Best,

Dennis

**Comment by bitzj2015** [comment]
Hi, it is in `llvm/build/bin`.

**Comment by yzhang71** [comment]
Hi team,

Thanks for replying! I have fixed that issue above. However, when I tried to run SanRazor with CPU2006, it always gives me build error. Here is the log file. Could you please take a look? Thank you so much.

Best,

Dennis
[build_log.txt](https://github.com/SanRazor-repo/SanRazor/files/6604936/build_log.txt)

**Comment by bitzj2015** [comment]
Hi Dennis,

It seems that you did not install `parallel`, since the error said: `cannot load such file -- parallel ... from /home/dennis/SanRazor/llvm/build/bin//SanRazor-clang:24:in `<main>'`. Can you check this?

Best wishes,
Jiang
